# Generated by Django 2.2.4 on 2019-10-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shu2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enen',
        ),
        migrations.DeleteModel(
            name='newdea',
        ),
    ]
