# Generated by Django 2.2.4 on 2019-09-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gongyingshang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('provide_item', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('CEO', models.CharField(max_length=32)),
                ('t', models.ManyToManyField(to='shu.Gongyingshang')),
            ],
        ),
        migrations.CreateModel(
            name='Cellphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xinghao', models.CharField(max_length=32)),
                ('pingmudaxiao', models.IntegerField()),
                ('m', models.ForeignKey(on_delete=False, to='shu.Industry')),
            ],
        ),
    ]
