# Generated by Django 2.2.4 on 2019-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gongyingnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('provide_item', models.CharField(max_length=32)),
            ],
        ),
    ]
